name: weatherforecast-$(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
    - 'master'

jobs:
- job:
  variables:
    - name: vmImagePool
      value: windows-2019
  pool:
    vmImage: $(vmImagePool)
  steps:
  - checkout: self
    clean: false
    fetchDepth: 1
    persistCredentials: true

  - script: set
    displayName: Show variables
  
  - task: UseDotNet@2
    displayName: Use .NET Core 3.x
    inputs:
      version: 3.x
    
  - task: NuGetToolInstaller@1
    displayName: Use NuGet 5.4.0
    inputs:
      versionSpec: 5.4.0
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      command: restore
      restoreSolution: FeatherForecast.sln
      #vstsFeed: a6632064-1b3c-4ec3-bb11-e719e5fe5aed


  - task: MSBuild@1
    displayName: Build project
    inputs:
      solution: 'FeatherForecast/FeatherForecast.csproj'
      platform: AnyCPU
      configuration: Release
      msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)" /p:Version=$(buildVersion)'
      maximumCpuCount: true


  - task: CopyFiles@2
    displayName: Copy version.txt
    inputs:
      #sourceFolder: $(Build.SourcesDirectory)
      contents: version.txt
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: CopyFiles@2
    displayName: Copy SoloJet.Tests
    inputs:
      #sourceFolder: $(Build.SourcesDirectory)
      contents: 'SoloJet.Tests\**'
      targetFolder: $(Build.ArtifactStagingDirectory)
      
  - task: PublishBuildArtifacts@1
    displayName: Publish artifact
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      # release pipeline expects this name
      artifactName: ReleasePack
      parallel: false

